- .github/workflows/release.yml
- CycloneDX.Utils.Tests/CycloneDX.Utils.Tests.csproj
- CycloneDX.Utils.Tests/MergeTests.cs
- CycloneDX.Utils/CycloneDX.Utils.csproj
- CycloneDX.Utils/Merge.cs
- CycloneDXLibrary.sln
> Implement basic SBOM component merging

- CycloneDX.Utils.Tests/ComponentVersionDiffTests.cs
- CycloneDX.Utils.Tests/TestHelpers.cs
- CycloneDX.Utils/ComponentVersionDiff.cs
- CycloneDX.Utils/Merge.cs
> Implement component version diff

- CycloneDX.Utils.Tests/ComponentVersionDiffTests.cs
- CycloneDX.Utils.Tests/MultipleComponentVersionsTests.cs
- CycloneDX.Utils.Tests/TestHelpers.cs
- CycloneDX.Utils/ComponentAnalysisIdentifier.cs
- CycloneDX.Utils/ComponentVersionDiff.cs
- CycloneDX.Utils/Merge.cs
- CycloneDX.Utils/MultipleComponentVersions.cs
> Analysis for multiple component versions

- CycloneDX.Core/Models/v1_0/Bom.cs
- CycloneDX.Core/Models/v1_1/Bom.cs
- CycloneDX.Core/Models/v1_2/Bom.cs
- CycloneDX.Core/Models/v1_3/Bom.cs
> Make version optional as per XML schema

- CycloneDX.Core.Tests/MediaTypeTests.cs
- CycloneDX.Core/Format.cs
- CycloneDX.Core/MediaTypes.cs
> Add format and media type helpers

- CycloneDX.Core.Tests/Protobuf/v1.3/SerializationTests.cs
- CycloneDX.Core.Tests/Protobuf/v1.3/ValidationTests.cs
- CycloneDX.Core/Json/Deserializer.cs
- CycloneDX.Core/Json/Serializer.cs
- CycloneDX.Core/Json/Validator.cs
- CycloneDX.Core/Protobuf/Deserializer.cs
- CycloneDX.Core/Protobuf/Serializer.cs
- CycloneDX.Core/Xml/Deserializer.cs
- CycloneDX.Core/Xml/Serializer.cs
- CycloneDX.Core/Xml/Validator.cs
> Add additional serialization/deserialization methods that utilise streams

- CycloneDX.Core/Xml/Serializer.cs
> Set encoding when writing to a stream

- CycloneDX.Utils.Tests/MergeTests.cs
- CycloneDX.Utils.Tests/__snapshots__/MergeTests.HierarchicalMergeComponentsTest.snap
- CycloneDX.Utils/Merge.cs
> Fix for hierarchical merge not including dependency refs for BOM subject

- CycloneDX.Utils.Tests/RemoveInternalPropertiesTests.cs
- CycloneDX.Utils/RemoveInternalProperties.cs
> Add utility method to remove internal properties from a BOM

- CycloneDX.Core.Tests/Protobuf/v1.3/SerializationTests.cs
- CycloneDX.Core/Json/Deserializer.cs
- CycloneDX.Core/Protobuf/Serializer.cs
- CycloneDX.Core/Xml/Deserializer.cs
> Fix incorrect handling of non-seekable streams

- CycloneDX.Core.Tests/Json/SerializationTests.cs
- CycloneDX.Core.Tests/Json/__snapshots__/SerializationTests.JsonRoundTripAsyncTest_valid-bom-1.2.json.snap
- CycloneDX.Core.Tests/Json/__snapshots__/SerializationTests.JsonRoundTripAsyncTest_valid-bom-1.3.json.snap
- CycloneDX.Core.Tests/Json/__snapshots__/SerializationTests.JsonRoundTripTest_valid-bom-1.2.json.snap
- CycloneDX.Core.Tests/Json/__snapshots__/SerializationTests.JsonRoundTripTest_valid-bom-1.3.json.snap
- CycloneDX.Core/Json/Deserializer.cs
- CycloneDX.Core/Xml/Deserializer.cs
> Fix for non-version specific deserialization stream position handling

- CycloneDX.Core/Json/Validator.cs
- CycloneDX.Core/Xml/Validator.cs
- CycloneDX.Utils.Tests/GenerateSerialNumberTests.cs
- CycloneDX.Utils/GenerateSerialNumber.cs
> Add handling for validating poorly formed XML or JSON and serial number helper method

- docs/articles/getting-started.md
- docs/index.md
- src/CycloneDX.Core/Xml/Validator.cs
- tests/CycloneDX.Core.Tests/Xml/v1.0/ValidationTests.cs
- tests/CycloneDX.Core.Tests/Xml/v1.1/ValidationTests.cs
- tests/CycloneDX.Core.Tests/Xml/v1.2/ValidationTests.cs
- tests/CycloneDX.Core.Tests/Xml/v1.3/ValidationTests.cs
> Add getting started article and fix up out of place xml async validation

- src/CycloneDX.Core/Models/Vulnerabilities/ImpactAnalysisState.cs
Signed-off-by: nscuro <nscuro@protonmail.com>
> Fix typo in XML name of `ImpactAnalysisState.Resolved`

- .github/workflows/dotnetcore.yml
- .gitpod.yml
- src/CycloneDX.Spdx/Models/v2_2/RelationshipType.cs
- src/CycloneDX.Spdx/Schemas/spdx-2.2.schema.json
> Update SPDX JSON schema

- src/CycloneDX.Core/Models/Vulnerabilities/Vulnerability.cs
> Add properties to vulnerabilities

- src/CycloneDX.Core/Json/Validator.cs
- tests/CycloneDX.Core.Tests/Json/ValidationTests.cs
- tests/CycloneDX.Core.Tests/Json/v1.4/ValidationTests.cs
- tests/CycloneDX.Core.Tests/Resources/v1.4/invalid-bomattribute-1.4.json
Improve the JSON validation by:
- Adding a function to validate against any specification version
- Improving the validation output (report the InstanceLocation on which the validation failed)
> Improve JSON validation

- src/CycloneDX.Core/Json/Utils.cs
- tests/CycloneDX.Core.Tests/Json/v1.5/__snapshots__/SerializationTests.JsonRoundTripAsyncTest_valid-evidence-1.5.json.snap
- tests/CycloneDX.Core.Tests/Json/v1.5/__snapshots__/SerializationTests.JsonRoundTripTest_valid-evidence-1.5.json.snap
Helps to address https://github.com/CycloneDX/cyclonedx-cli/issues/358
> Fix serialization of EvidenceFieldType

- src/CycloneDX.Core/Json/Utils.cs
- tests/CycloneDX.Core.Tests/Json/v1.5/ValidationTests.cs
- tests/CycloneDX.Core.Tests/Json/v1.5/__snapshots__/SerializationTests.JsonRoundTripAsyncTest_valid-formulation-1.5.json.snap
- tests/CycloneDX.Core.Tests/Json/v1.5/__snapshots__/SerializationTests.JsonRoundTripTest_valid-formulation-1.5.json.snap
Fix serialization of enums VolumeMode and DataType
Add also a test to validate the sbom after serialization round trip.
> Fix enum serialization

- src/CycloneDX.Core/Json/Converters/DateTimeConverter.cs
Addresses: https://github.com/CycloneDX/cyclonedx-cli/issues/383
> Use invariant culture when de-/serializing DateTime

- src/CycloneDX.Core/Json/Serializer.Serialization.cs
- src/CycloneDX.Core/Models/Component.cs
- src/CycloneDX.Core/Models/Declarations/Assessor.cs
- src/CycloneDX.Core/Models/Declarations/Attestation.cs
- src/CycloneDX.Core/Models/Declarations/Claim.cs
- src/CycloneDX.Core/Models/Declarations/DeclarationsEvidence.cs
- src/CycloneDX.Core/Models/Definitions/Level.cs
- src/CycloneDX.Core/Models/Definitions/Requirement.cs
- src/CycloneDX.Core/Models/Definitions/Standard.cs
- src/CycloneDX.Core/Models/Interfaces/IHasBomRef.cs
- src/CycloneDX.Core/Models/OrganizationalEntity.cs
- src/CycloneDX.Core/Models/Service.cs
- src/CycloneDX.Utils/Merge.cs
- tests/CycloneDX.Utils.Tests/__snapshots__/MergeTests.HierarchicalMergeComponentsTest.snap
- tests/CycloneDX.Utils.Tests/__snapshots__/MergeTests.HierarchicalMergeDuplicatedToolsComponentsTest.snap
- tests/CycloneDX.Utils.Tests/__snapshots__/MergeTests.HierarchicalMergeToolsComponentsTest.snap
- tests/CycloneDX.Utils.Tests/__snapshots__/MergeTests.HierarchicalMergeVulnerabilitiesTest.snap
If I understand correctly, every reference will simply be namespaced with this.
> merge attestations and standards

- src/CycloneDX.Core/Models/LicenseChoice.cs
Addresses https://github.com/CycloneDX/cyclonedx-cli/issues/398
> Fix xml deserialization of licenses with namespace prefix

- src/CycloneDX.Core/Models/Workspace.cs
- tests/CycloneDX.Core.Tests/Json/v1.5/__snapshots__/SerializationTests.JsonRoundTripAsyncTest_valid-formulation-1.5.json.snap
- tests/CycloneDX.Core.Tests/Json/v1.5/__snapshots__/SerializationTests.JsonRoundTripTest_valid-formulation-1.5.json.snap
- tests/CycloneDX.Core.Tests/Json/v1.6/__snapshots__/SerializationTests.JsonRoundTripAsyncTest_valid-formulation-1.6.json.snap
- tests/CycloneDX.Core.Tests/Json/v1.6/__snapshots__/SerializationTests.JsonRoundTripTest_valid-formulation-1.6.json.snap
- tests/CycloneDX.Core.Tests/Xml/v1.5/__snapshots__/SerializationTests.XmlRoundTripStreamTest_valid-formulation-1.5.xml.snap
- tests/CycloneDX.Core.Tests/Xml/v1.5/__snapshots__/SerializationTests.XmlRoundTripTest_valid-formulation-1.5.xml.snap
- tests/CycloneDX.Core.Tests/Xml/v1.6/__snapshots__/SerializationTests.XmlRoundTripStreamTest_valid-formulation-1.6.xml.snap
- tests/CycloneDX.Core.Tests/Xml/v1.6/__snapshots__/SerializationTests.XmlRoundTripTest_valid-formulation-1.6.xml.snap
Closes: https://github.com/CycloneDX/cyclonedx-dotnet-library/issues/357
> Fix AccessMode such that it is optional

- src/CycloneDX.Core/Json/Validator.cs
Addresses: https://github.com/CycloneDX/cyclonedx-cli/issues/407
> Avoid misleading validation error messages

- src/CycloneDX.Core/Models/Vulnerabilities/Rating.cs
Addresses: https://github.com/CycloneDX/cyclonedx-cli/issues/409
> Fix serialization of Rating

- src/CycloneDX.Spdx.Interop/Converters/v2_2/Helpers/SpdxDocumentHelpers.cs
I tried a small fix for the issue I just opened. Please modify if necessary.
Fixes #363
> Fix conversion of supplier without contact list

- src/CycloneDX.Core/Models/Vulnerabilities/Status.cs
Helps to resolve: https://github.com/CycloneDX/cyclonedx-cli/issues/423
> Fix vulnerability Status enum
